Initial Setup
mckent05/Javascript_Capstone pull request #22
Opened 2021-11-15 15:18 UTC by brytebee

## In this PR, we accomplished the following:
- Installed webpack
- Installed linters
- Installed Jest
- We implemented GitFlow
- Setup GitHub project with Kanban board

2021-11-15 15:57 UTC, mckent05 requested changes
Hello @brytebee 👋 

You have done a great job on this project so far 💪 

## Suggested Changes ♻️ 

However, there are still some required changes you need to implement to get this project approved.

_Find below the required/ optional changes in the commented sections._

Ask for another code review implementing the changes

**_Happy coding 👍 👍_**

2021-11-15 15:57 UTC, mckent05 commented on linters.sh
> +npm install --save-dev eslint@7.x eslint-config-airbnb-base@14.x eslint-plugin-import@2.x babel-eslint@10.x
- [**REQUIRED**] Please remove all personal scripts as this is not part of the project requirements.

2021-11-15 15:57 UTC, mckent05 commented on webpack_within_project_file.sh
> +npm install --save-dev webpack-dev-server
[**REQUIRED**] As explained previously in your `linters.sh` remove all scripts

2021-11-15 16:25 UTC, brytebee commented
Hello @name 👋👋,

Thanks for the warm-hearted review 👀👀.
I'll go ahead to implement the requested changes ♻️ and ask for a re-review!

2021-11-15 23:07 UTC, mckent05 approved these changes
Hello @brytebee 👋 

Well done on implementing the previously requested changes 👍 . There's nothing else to say than, it's time to merge it


Congratulations! 🎉 . Cheers and Happy coding: 👏 👏 👏

2021-11-16 08:20 UTC, brytebee commented
Hello @mckent05 👋👋,

Thanks for the warm-hearted review 👀👀.
I'll go ahead to merge and move on to the next milestone 🏁🏁.

**_Happy Hacking 😄😄_**

2021-11-16 08:20 UTC, merged